# Generated by Django 6.0.1 on 2026-01-14 18:14

import entries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=entries.models.get_upload_path),
        ),
    ]
