# Generated by Django 6.0.1 on 2026-01-14 21:15

import django.db.models.deletion
import entries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_journalentry_is_published_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('run', 'Run'), ('hike', 'Hike'), ('adventure', 'Adventure'), ('community', 'Community Event'), ('wellness', 'Wellness'), ('other', 'Other')], default='adventure', max_length=20)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=entries.models.get_upload_path)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Path Event',
                'verbose_name_plural': 'Path Events',
                'ordering': ['event_date'],
            },
        ),
    ]
