# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_diarypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathevent',
            name='event_end_date',
            field=models.DateTimeField(blank=True, help_text='End date & time (optional)', null=True),
        ),
    ]
