# Generated by Django 6.0.1 on 2026-02-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_pathevent_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathevent',
            name='event_date',
            field=models.DateTimeField(help_text='Start date & time'),
        ),
    ]
