# Generated by Django 6.0.1

import django.db.models.deletion
import entries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_alter_pathevent_event_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=entries.models.media_library_upload_path)),
                ('title', models.CharField(blank=True, help_text='Optional label', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media item',
                'verbose_name_plural': 'Media library',
                'ordering': ['-created_at'],
            },
        ),
    ]
