# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
